# ----
# Site

title: Crea Developer
description: Crea Developer Documentation.
baseurl: '/'
url: https://developers.creaproject.io
google_analytics_key: UA-76480270-4
permalink: /:categories/:title.html

collections:
  introduction:
    title: Introduction
    id: introduction
    position: 1
    output: true
  contributors:
    title: Contributors
    id: contributors
    position: 2
    output: true
  quickstart:
    title: Quickstart
    id: quickstart
    position: 3
    output: true
  javascript:
    title: Javascript
    id: javascript
    position: 4
    output: true
  services:
    title: Services
    id: services
    position: 6
    output: true
  resources:
    title: Resources
    id: resources
    position: 7
    output: true
  glossary:
    title: Glossary
    id: glossary
    position: 8
    output: true
  apidefinitions:
    title: API Definitions
    id: apidefinitions
    position: 12
    output: true
  testnet:
    title: Testnet
    id: testnet
    position: 13
    output: true
  tutorials-ruby:
    title: Ruby Tutorials
    id: tutorials-ruby
    position: 14
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  - vendor
  - Makefile

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post

kramdown:
  auto_ids: true
  
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CONTRIBUTING.md']
